services:
  mongodb:
    image: mongo:7
    container_name: sparx-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - sparx-mongodb-data:/data/db

volumes:
  sparx-mongodb-data:
